apiVersion: v1
kind: Service
metadata:
  name: mon-application
spec:
  type: NodePort
  ports:
    - port: 5000            # Port exposé par le service
      targetPort: 5000      # Port du conteneur
      nodePort: 30001      # Port externe (facultatif, Minikube choisira un port si non spécifié)
  selector:
    app: mon-application