# Generated by Django 5.1.6 on 2025-02-09 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_post_delete_article_delete_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='part1',
            field=models.TextField(default='Contenu'),
        ),
        migrations.AddField(
            model_name='post',
            name='part2',
            field=models.TextField(default='Contenu'),
        ),
        migrations.AddField(
            model_name='post',
            name='part3',
            field=models.TextField(default='Contenu'),
        ),
        migrations.AddField(
            model_name='post',
            name='part4',
            field=models.TextField(default='Contenu'),
        ),
        migrations.AddField(
            model_name='post',
            name='part5',
            field=models.TextField(default='Contenu'),
        ),
        migrations.AddField(
            model_name='post',
            name='part6',
            field=models.TextField(default='Contenu'),
        ),
        migrations.AddField(
            model_name='post',
            name='part7',
            field=models.TextField(default='Contenu'),
        ),
        migrations.AddField(
            model_name='post',
            name='part8',
            field=models.TextField(default='Contenu'),
        ),
        migrations.AddField(
            model_name='post',
            name='part9',
            field=models.TextField(default='Contenu'),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='blog.post')),
            ],
        ),
    ]
