# Generated by Django 5.1.6 on 2025-02-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_part1_post_part2_post_part3_post_part4_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commentaire',
        ),
    ]
