name: CI/CD for Django

on:
  push:
    branches:
      - main  # Changez cela en fonction de votre branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Changez en fonction de votre version de Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build  # S'assure que le build est terminé avec succès

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LOCAL_VM_HOST }}  # Remplacez par l'IP ou le nom d'hôte de votre VM
          username: ${{ secrets.LOCAL_VM_USER }}  # Nom d'utilisateur sur la VM
          key: ${{ secrets.LOCAL_VM_SSH_KEY }}  # Clé SSH pour l'authentification
          port: 22  # Port SSH
          source: "."
          target: "~/home/sanablog"  

      - name: Run deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LOCAL_VM_HOST }}
          username: ${{ secrets.LOCAL_VM_USER }}
          key: ${{ secrets.LOCAL_VM_SSH_KEY }}
          port: 22
          script: |
            cd ~/home/sanablog
            source venv/bin/activate 
            python manage.py migrate 
            python manage.py collectstatic --noinput 
            systemctl restart gunicorn
